In [24]:
import pandas as pd
from IPython.display import display

df = pd.read_csv("C:/Final_Capstone_Project/producer/data/fraudTrain.csv")

#=====================Data Quality Checks=======================================================================

print("DataFrame Loaded Successfully and ready for analysis.")
print("DataFrame Shape:", df.shape) # Display the shape of the DataFrame
print("DataFrame Columns:")
display(df.columns) # Display the column names
print("First 5 Rows:")
display(df.head(5)) # Display the first 5 rows of the DataFrame
print("Data Types:")
display(df.dtypes)
print("DataFrame Information:")
display(df.info())
print("Summary Statistics:")
display(df.describe())
print("Duplicate Rows:")
display(df.duplicated().sum()) # Count duplicate rows
print("Null Values:")
display(df.isnull().sum()) # Count null values in each column
print("Unique Values:")
display(df.nunique()) # Count unique values in each column
print("Value Counts for is_fraud:")    #this will give the value counts for the is_fraud column
display(df['is_fraud'].value_counts(normalize=True))
display(df['amt'].describe())  #this do a outlier analysis on the amount column
display(df.groupby('is_fraud')['amt'].describe())  #this does a outlier analysis on the amount split by the is_fraud column


#======================Top 10 breakdowns on categorical columns for fraud analysis=========================================


df['category'].value_counts().head(10) #counts how many transactions fall into each category regardless of fraud status
#df[df['is_fraud'] == 1]['category'].value_counts().head(10) #counts how many fraudulent transactions fall into each category
display(df.groupby('category')['is_fraud'].mean().sort_values(ascending=False).head(10)) #calculates the percentage of fraudulent transactions in each category and sorts them in descending order
display(df.groupby('category')['amt'].mean().sort_values(ascending=False).head(10)) #calculates the average/biggest transaction amount in each category and sorts them in descending order

merchant_counts = df['merchant'].value_counts()
valid_merchants = merchant_counts[merchant_counts >= 100].index  # only merchants with 100+ transactions
display(df[df['merchant'].isin(valid_merchants)].groupby('merchant')['is_fraud'].mean().sort_values(ascending=False).head(10))
display(df[df['merchant'].isin(valid_merchants)].groupby('merchant')['amt'].mean().sort_values(ascending=False).head(10))

df['state'].value_counts().head(10) #counts how many transactions fall into each state regardless of fraud status
display(df.groupby('state')['is_fraud'].mean().sort_values(ascending=False).head(10)) #calculates the percentage of fraudulent transactions in each state and sorts them in descending order
display(df.groupby('state')['amt'].mean().sort_values(ascending=False).head(10)) #calculates the average/biggest transaction amount in each state and sorts them in descending order

df['job'].value_counts().head(10) #counts how many transactions fall into each job regardless of fraud status
display(df.groupby('job')['is_fraud'].mean().sort_values(ascending=False).head(10)) #calculates the percentage of fraudulent transactions in each job and sorts them in descending order
display(df.groupby('job')['amt'].mean().sort_values(ascending=False).head(10)) #calculates the average/biggest transaction amount in each job and sorts them in descending order

df['gender'].value_counts().head(2) #counts how many transactions fall into each gender regardless of fraud status
display(df.groupby('gender')['is_fraud'].mean().sort_values(ascending=False).head(2)) #calculates the percentage of fraudulent transactions in each gender and sorts them in descending order
display(df.groupby('gender')['amt'].mean().sort_values(ascending=False).head(2)) #calculates the average/biggest transaction amount in each gender   


#====================columns update===================================================================

df = df.drop(columns=['Unnamed: 0'])

df = df.rename(columns={
    'trans_num': 'transaction_id',
    'trans_date_trans_time': 'event_timestamp', 
    'first': 'customer_first_name',
    'last': 'customer_last_name'
})

df.to_csv("C:/Final_Capstone_Project/producer/data/fraudTrain_clean.csv", index=False)

DataFrame Loaded Successfully and ready for analysis.
DataFrame Shape: (1296675, 23)
DataFrame Columns:

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

First 5 Rows:

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

Data Types:

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
gender                    object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

None

Summary Statistics:

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,6.483370e+05,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

Duplicate Rows:

np.int64(0)

Null Values:

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

Unique Values:

Unnamed: 0               1296675
trans_date_trans_time    1274791
cc_num                       983
merchant                     693
category                      14
amt                        52928
first                        352
last                         481
gender                         2
street                       983
city                         894
state                         51
zip                          970
lat                          968
long                         969
city_pop                     879
job                          494
dob                          968
trans_num                1296675
unix_time                1274823
merch_lat                1247805
merch_long               1275745
is_fraud                       2
dtype: int64

Value Counts for is_fraud:

is_fraud
0    0.994211
1    0.005789
Name: proportion, dtype: float64

count    1.296675e+06
mean     7.035104e+01
std      1.603160e+02
min      1.000000e+00
25%      9.650000e+00
50%      4.752000e+01
75%      8.314000e+01
max      2.894890e+04
Name: amt, dtype: float64

,count,mean,std,min,25%,50%,75%,max
is_fraud,,,,,,,,
0,1289169.0,67.667110,154.007971,1.00,9.6100,47.280,82.540,28948.90
1,7506.0,531.320092,390.560070,1.06,245.6625,396.505,900.875,1376.04

category
shopping_net     0.017561
misc_net         0.014458
grocery_pos      0.014098
shopping_pos     0.007225
gas_transport    0.004694
misc_pos         0.003139
grocery_net      0.002948
travel           0.002864
entertainment    0.002478
personal_care    0.002424
Name: is_fraud, dtype: float64

category
grocery_pos      116.960986
travel           111.504720
shopping_net      88.424076
misc_net          80.865095
shopping_pos      79.779155
entertainment     64.210421
gas_transport     63.434572
misc_pos          62.890999
home              58.270139
kids_pets         57.536871
Name: amt, dtype: float64

merchant
fraud_Kozey-Boehm                       0.025723
fraud_Herman, Treutel and Dickens       0.025385
fraud_Kerluke-Abshire                   0.022307
fraud_Brown PLC                         0.022109
fraud_Goyette Inc                       0.021616
fraud_Terry-Huel                        0.021543
fraud_Jast Ltd                          0.021505
fraud_Schmeler, Bashirian and Price     0.020833
fraud_Boyer-Reichert                    0.019916
fraud_Langworth, Boehm and Gulgowski    0.019807
Name: is_fraud, dtype: float64

merchant
fraud_Boyer-Haley                       165.653477
fraud_Little-Gleichner                  163.045134
fraud_Monahan, Hermann and Johns        158.763321
fraud_Champlin, Rolfson and Connelly    156.062488
fraud_Eichmann, Hayes and Treutel       147.332197
fraud_Kunze, Larkin and Mayert          141.453333
fraud_Tillman LLC                       135.533146
fraud_Medhurst, Labadie and Gottlieb    134.026653
fraud_Hackett Group                     133.157821
fraud_Reichel, Bradtke and Blanda       129.397857
Name: amt, dtype: float64

state
DE    1.000000
RI    0.027273
AK    0.016981
NV    0.008382
CO    0.008141
OR    0.008012
TN    0.007975
NE    0.007448
ME    0.007210
NH    0.007127
Name: is_fraud, dtype: float64

state
DE    514.493333
VT     82.095346
RI     81.939400
CO     78.542602
NC     76.977511
DC     76.699546
WY     75.758228
AR     75.255207
AZ     75.053438
LA     74.958423
Name: amt, dtype: float64

job
Personnel officer                 1.0
Air traffic controller            1.0
Accountant, chartered             1.0
Ship broker                       1.0
Solicitor                         1.0
Careers adviser                   1.0
Information officer               1.0
Armed forces technical officer    1.0
Industrial buyer                  1.0
Homeopath                         1.0
Name: is_fraud, dtype: float64

job
Ship broker                          874.505714
Engineer, site                       732.478333
Air traffic controller               719.814118
Contracting civil engineer           700.092857
Sales promotion account executive    691.478571
Industrial buyer                     680.775000
Dancer                               644.929474
Homeopath                            642.447273
Careers adviser                      625.602000
Veterinary surgeon                   603.951250
Name: amt, dtype: float64

gender
M    0.006426
F    0.005262
Name: is_fraud, dtype: float64

gender
M    70.533350
F    70.200324
Name: amt, dtype: float64